package com.tikitaka.document.dto.response;
import java.util.List;
import java.util.UUID;
import com.tikitaka.document.entity.RevisionStatus;
public record DocumentRevisionDetailResponse(
        UUID revisionId,
        UUID documentId,
        RevisionStatus status,
        Integer baseDocumentVersion,
        Integer previewVersion,
        String title,
        String sourceFileName,
        String sourcePdfUrl,
        Integer sourcePageCount,
        List<RevisionSourceSlideResponse> revisionSlides,
        List<RevisionPageResponse> previewPages,
        boolean canUndo,
        boolean canRedo
) {}
